import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Header from '@/components/layout/header/Header';
import Footer from '@/components/layout/footer/Footer';
import './globals.css';
import SmoothScrollHandler from '@/components/ui/ScrollHandler';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Ai's Portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SmoothScrollHandler
          scrollSpeed={0.4} // スクロール速度（遅く: 0.1, 速く: 1.0）
          smoothness={0.08} // 滑らかさ（滑らか: 0.05, 素早く: 0.15）
          enableSmooth={true} // 滑らかスクロールのON/OFF
        />{' '}
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
